In [25]:
#importing libraries
import pandas as pd
import numpy as np

In [26]:
#reading data
df = pd.read_csv('/workspaces/new_python_test/data/cafe_sales.csv')

In [27]:
#inspecting first few rows
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,INA,INA,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [28]:
#inspecting last few rows
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9535,TXN_7672686,Coffee,2,2.0,4.0,INA,INA,2023-08-30
9536,TXN_9659401,Juice,3,3.0,3.0,Digital Wallet,INA,2023-06-02
9537,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,INA,2023-03-02
9538,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,INA,2023-12-02
9539,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [29]:
#data structure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9540 entries, 0 to 9539
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9540 non-null   str
 2   Quantity          9540 non-null   int64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 596.4 KB

In [30]:
#duplicate record
print(f'Number of duplicate records: {sum(df.duplicated())}')

Number of duplicate records: 0

In [31]:
#missing record
df.isna().sum()*100 / df.shape[0]

Transaction ID      0.0
Item                0.0
Quantity            0.0
Price Per Unit      0.0
Total Spent         0.0
Payment Method      0.0
Location            0.0
Transaction Date    0.0
dtype: float64

In [32]:
#unique record
df_columns = set(df.columns)
exclude = {'Transaction ID'}
df_columns = df.columns.difference(exclude)

for column in df_columns:
    print(f'{column}: \n {df[column].unique()}', '\n\n')

Item:
 <StringArray>
['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Juice', 'Sandwich', 'Tea']
Length: 8, dtype: str


Location:
 <StringArray>
['Takeaway', 'In-store', 'INA']
Length: 3, dtype: str


Payment Method:
 <StringArray>
['Credit Card', 'Cash', 'INA', 'Digital Wallet']
Length: 4, dtype: str


Price Per Unit:
 [2.  3.  1.  5.  4.  1.5]


Quantity:
 [2 4 5 3 1]


Total Spent:
 [ 4.  12.  10.  20.   9.  16.  15.  25.   8.   5.   3.   6.   2.   1.
  7.5  4.5  1.5]


Transaction Date:
 <StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 365, dtype: str

In [33]:
#replacing ERROR and UNKNOWN values
df = df.replace(['ERROR', 'UNKNOWN'], np.nan)

In [34]:
#missing record after treating "ERROR" & "UNKNOWN"
df.isna().sum()*100 / df.shape[0]

Transaction ID      0.0
Item                0.0
Quantity            0.0
Price Per Unit      0.0
Total Spent         0.0
Payment Method      0.0
Location            0.0
Transaction Date    0.0
dtype: float64

In [35]:
#data type converstion
df['Quantity'] = df['Quantity'].astype('Int64')
df[['Price Per Unit', 'Total Spent']] = df[['Price Per Unit', 'Total Spent']].astype('float')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9540 entries, 0 to 9539
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   str
 1   Item              9540 non-null   str
 2   Quantity          9540 non-null   Int64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   str
 6   Location          9540 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 605.7 KB

In [37]:
#dropping record where Transaction Date is not available
df = df.dropna(subset = 'Transaction Date')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,INA,INA,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9535,TXN_7672686,Coffee,2,2.0,4.0,INA,INA,2023-08-30
9536,TXN_9659401,Juice,3,3.0,3.0,Digital Wallet,INA,2023-06-02
9537,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,INA,2023-03-02
9538,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,INA,2023-12-02
9539,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [38]:
#replacing missing record in "Payment Method" & "Location" with "INA"
df[['Payment Method', 'Location']] = df[['Payment Method', 'Location']].fillna('INA')

In [39]:
#replacing missing record in "Item" with mode value
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])

In [40]:
#replacing missing record in "Quantity" with median value
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [41]:
#inspecting item "Price Per Unit"
df.groupby('Item')['Price Per Unit'].value_counts()

Item      Price Per Unit
Cake      3.0               1082
Coffee    2.0               1123
Cookie    1.0               1035
Juice     3.0               1398
          4.0                202
          2.0                116
          5.0                115
          1.0                112
          1.5                108
Salad     5.0               1099
Sandwich  4.0               1075
Smoothie  4.0               1048
Tea       1.5               1027
Name: count, dtype: int64

In [42]:
#filling missing record in "Price Per Unit" with mode value of Item category
df['Price Per Unit'] = df.groupby('Item')['Price Per Unit'].transform(lambda x: x.fillna(x.mode()[0]))

In [43]:
#filling missing record in "Total Spent"
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

In [44]:
#saving cleaned file
df.to_csv('/workspaces/new_python_test/data/cafe_sales (cleaned).csv', index = False)